./add_booktext.py A_Charm_me_a_Rechad_a_Osisiu_el_Kaubeltik-Clara_Orrenges..txt "A Charm me a Rechad a Osisiu el Kaubeltik"
./add_booktext.py Ak_Milekera_er_a_Ulengull_er_a_Skuul-Masaharu_Tmodrang..txt "Ak Milekera er a Ulengull er a Skuul"
./add_booktext.py Beltik_el_Reng-Tina_Rehuher..txt "Beltik el Reng"
./add_booktext.py Charm_me_a_Klengar-Rachel_Nabeyama..txt "Charm me a Klengar"
./add_booktext.py Chisel_a_Bebil_er_a_Charm-Rachel_Nabeyama..txt "Chisel a Bebil er a Charm"
./add_booktext.py Hansel_me_a_Gretel-Teodosia_Faustino..txt "Hansel me a Gretel"
./add_booktext.py Ius_me_a_Uel-Maria_Otto..txt "Ius me a Uel"
./add_booktext.py Kakerous_a_Meklungel_me_a_Teletelel-Rachel_Nabeyama..txt "Kakerous a Meklungel me a Teletelel"
./add_booktext.py Kakerous_el_Cheldecheduch-Ymesei_Ezekiel..txt "Kakerous el Cheldecheduch"
./add_booktext.py Kakerous_el_Tekoi-Yosko_Malsol..txt "Kakerous el Tekoi"
./add_booktext.py Ke_Mle_Medenge_el_Kmo_Demul_a_-Mahensia_Thomas..txt "Ke Mle Medenge el Kmo Demul a "
./add_booktext.py Ke_Orrenges_Ng_Diak-Rachel_Nabeyama..txt "Ke Orrenges Ng Diak"
./add_booktext.py Kede_Kausisbech-Rachel_Nabeyama..txt "Kede Kausisbech"
./add_booktext.py Kemril_a_Ngikel-Toyoko_Ruluked..txt "Kemril a Ngikel"
./add_booktext.py Keo_me_a_Moku-Theodosia_Faustino..txt "Keo me a Moku"
./add_booktext.py Klaungalek_me_a_Klauchad-Rachel_Nabeyama..txt "Klaungalek me a Klauchad"
./add_booktext.py Klekedall_Me_A_Teletael_Me_A_Ngerachel-Herman_Teriong..txt "Klekedall Me A Teletael Me A Ngerachel"
./add_booktext.py Korki_el_Klaidesachel-Rachel_Nabeyama..txt "Korki el Klaidesachel-Rachel Nabeyama"
./add_booktext.py Lak_El_Chetim_El_Kau-Yosko_Malsol..txt "Lak El Chetim El Kau"
./add_booktext.py Llecheklel_me_a_Omesodel-Mahensia_Thomas..txt "Llecheklel me a Omesodel"
./add_booktext.py Mesaik_el_Mari-Rachel_Nabeyama..txt "Mesaik el Mari"
./add_booktext.py Momes_e_Monguiu_e_Mouchais-Rachel_Nabeyama..txt "Momes e Monguiu e Mouchais"
./add_booktext.py Monguiu_e_Moruul-Rachel_Nabeyama..txt "Monguiu e Moruul"
./add_booktext.py Ng_Ngara_mo_Duubech-Rachel_Nabeyama..txt "Ng Ngara mo Duubech"
./add_booktext.py Ng_Telechesuch_el_Omeruul-Miriam_U._Sakuma..txt "Ng Telechesuch el Omeruul"
./add_booktext.py Ngara_ng_Ousbech_a_Telungalek-Riosang_Salvador..txt "Ngara ng Ousbech a Telungalek"
./add_booktext.py Omengereomel_el_Belochel-Mahensia_Thomas..txt "Omengereomel el Belochel-Mahensia Thomas"
./add_booktext.py Omerolel_A_Elilai_El_Mo_Er_A_Beliliou-Maria_Otto..txt "Omerolel A Elilai El Mo Er A Beliliou"
./add_booktext.py Omesubel_a_Bebil_er_a_Dellomel_me_a_Charm-Maxie_T._Thomas..txt "Omesubel a Bebil er a Dellomel me a Charm"
./add_booktext.py Omilil_er_a_Iungs-Joelle_Arakaki..txt "Omilil er a Iungs"
./add_booktext.py Sechou_me_a_Deroech-Mahensia_Thomas..txt "Sechou me a Deroech"
./add_booktext.py Telungalek_er_a_Belau-Maxie_T._Thomas..txt "Telungalek er a Belau"
./add_booktext.py Teua_el_Chad_er_a_Chelitakl-PREL..txt "Teua el Chad er a Chelitakl"
./add_booktext.py Uchelel_a_Klengar-Rachel_Nabeyama..txt "Uchelel a Klengar"
./add_booktext.py Uldellomel_El_Reng-Maria_Rehuher..txt "Uldellomel El Reng"
./add_booktext.py Ungil_El_Dosuub-Katsue_Ngiruos..txt "Ungil El Dosuub"
./add_booktext.py lola.txt "Lola me a Lali"
./add_booktext.py ngerchebal..txt "Ngerchebal, Lice Island"
./add_booktext.py rengeldil.txt "Cheldechedechal a Rengeldil"
